server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.122.122:3306/mydb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver